<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="cad" nsURI="http://www.example.org/cad" nsPrefix="cad">
  <eClassifiers xsi:type="ecore:EClass" name="CAD_Model">
    <eOperations name="createFromString" eType="//EJavaObject">
      <eParameters name="eDataType" eType="//EDataType" />
      <eParameters name="literalValue" eType="//EString" />
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EJavaObject" instanceClassName="java.lang.Object" />
  <eClassifiers xsi:type="ecore:EDataType" name="EString" instanceClassName="java.lang.String">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="baseType" value="http://www.w3.org/2001/XMLSchema#string" />
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EDataType">
  </eClassifiers>
</ecore:EPackage>
